MvcOpdrachtTemplate/Controllers/CategorieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOpdrachtTemplate;
using MvcOpdrachtTemplate.BLL;
using MvcOpdrachtTemplate.Models;

namespace MvcOpdrachtTemplate.Controllers
{
    public class CategorieController : Controller
    {
        private CategorieBL _categorie = new CategorieBL();
        // GET: Categorie
        public ActionResult List()
        {
            return View(_categorie.GetAllCategorien());
        }

        // GET: Categorie/Details/5
        public ActionResult Details(int id)
        {
            return View(_categorie.GetCategorie(id));
        }

        // GET: Categorie/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categorie/Create
        [HttpPost]
        public ActionResult Create(Categorie categorie)
        {
            try
            {
                _categorie.CreateCategorie(categorie);

                return RedirectToAction("List");
            }
            catch
            {
                return View(categorie);
            }
        }

        // GET: Categorie/Edit/
        [Authorize]
        public ActionResult Edit(int id)
        {
            return View(_categorie.GetCategorie(id));
        }

        // POST: Categorie/Edit/5
        [HttpPost]
        public ActionResult Edit(Categorie categorie)
        {
            try
            {
                _categorie.UpdateCategorie(categorie);

                return RedirectToAction("List");
            }
            catch
            {
                return View(categorie);
            }
        }

        // GET: Categorie/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            return View(_categorie.GetCategorie(id));
        }

        // POST: Categorie/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                _categorie.DeleteCategorie(id);

                return RedirectToAction("List");
            }
            catch
            {
                return View(_categorie.GetCategorie(id));
            }
        }
    }
}

MvcOpdrachtTemplate/Controllers/ElektronischeComponentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOpdrachtTemplate.BLL;
using MvcOpdrachtTemplate.Models;


namespace MvcOpdrachtTemplate.Controllers
{
    public class ElektronischeComponentController : Controller
    {
        private ElektronischComponentBL _component = new ElektronischComponentBL();
        private CategorieBL _categorie = new CategorieBL();

        // GET: ElektronischeComponent
        public ActionResult List(string sortBy, string searchString)
        {
            ViewBag.Sort = string.IsNullOrEmpty(sortBy) ? "Name desc" : "";
            
            var namen = _component.getAllComponenten().AsQueryable();
           
            if (!String.IsNullOrEmpty(searchString))
            {
                namen = namen.Where(s => s.Naam.Contains(searchString));

            }
            switch (sortBy)
            {
                case "Name desc":
                    namen =namen.OrderByDescending(n => n.Naam);
                    break;
                default:
                    namen =namen.OrderBy(n => n.Naam);
                    break;
            }
            return View(namen.ToList());
        }

        // GET: ElektronischeComponent/Details/5
        public ActionResult Details(int id)
        {
            
            return View(_component.GetComponent(id));
        }

        // GET: ElektronischeComponent/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.CategorieId = new SelectList(_categorie.GetAllCategorien(), "Id", "Naam");
            return View();
        }

        // POST: ElektronischeComponent/Create
        [HttpPost]
        public ActionResult Create(ElektronischComponent component)
        {
            try
            {
                
                _component.CreateComponent(component);

                return RedirectToAction("List");
            }
            catch
            {
                ViewBag.CategorieId = new SelectList(_categorie.GetAllCategorien(), "Id", "Naam");
                return View(component);
            }
        }

        // GET: ElektronischeComponent/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            ViewBag.CategorieId = new SelectList(_categorie.GetAllCategorien(), "Id", "Naam");
            return View(_component.GetComponent(id));
        }

        // POST: ElektronischeComponent/Edit/5
        [HttpPost]
        public ActionResult Edit(ElektronischComponent component)
        {
            try
            {
                
                _component.UpdateComponent(component);

                return RedirectToAction("List");
            }
            catch
            {
                ViewBag.CategorieId = new SelectList(_categorie.GetAllCategorien(), "Id", "Naam");
                return View(component);
            }
        }

        // GET: ElektronischeComponent/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            return View(_component.GetComponent(id));
        }

        // POST: ElektronischeComponent/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
             
                _component.DeleteComponent(id);


                return RedirectToAction("List");
            }
            catch
            {
                return View(_component.GetComponent(id));
            }
        }
    }
}

MvcOpdrachtTemplate/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Stock App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Stock APP", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Componenten", "List", "ElektronischeComponent")</li>
                    <li>@Html.ActionLink("Categorieën", "List", "Categorie")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Stock APP</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>